apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-delete-chaos
  namespace: default
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=nginx'
    appkind: 'deployment'
  
  # Chaos Service Account
  chaosServiceAccount: pod-delete-sa
  
  # Monitoring
  monitoring: true
  
  # JobCleanUpPolicy
  jobCleanUpPolicy: 'delete'
  
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # Total chaos duration (seconds)
            - name: TOTAL_CHAOS_DURATION
              value: '60'
            
            # Number of pods to delete
            - name: PODS_AFFECTED_PERC
              value: '50'
            
            # Time between pod deletions
            - name: CHAOS_INTERVAL
              value: '10'
            
            # Force delete pods
            - name: FORCE
              value: 'true'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-delete-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-delete-sa
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create","delete","get","list","patch","update", "deletecollection"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","get","list","patch","update"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get","list","watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","list","get","delete","deletecollection"]
  - apiGroups: ["litmuschaos.io"]
    resources: ["chaosengines","chaosexperiments","chaosresults"]
    verbs: ["create","list","get","patch","update","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-delete-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-delete-sa
subjects:
- kind: ServiceAccount
  name: pod-delete-sa
  namespace: default
